import { Lead } from "./types";

export const getDefaultLead = (): Lead => ({
    id: "",
    submission_id: null,
    first_name: null,
    last_name: null,
    phone_number: null,
    email: null,
    ssn: null,
    state: null,
    address: null,
    city: null,
    zip_code: null,
    date_of_birth: null,
    birth_state: null,
    driver_license: null,
    age: null,
    height: null,
    weight: null,
    tobacco_use: null,
    health_conditions: null,
    medications: null,
    doctor_name: null,
    existing_coverage: null,
    desired_coverage: null,
    monthly_budget: null,
    draft_date: null,
    bank_name: null,
    routing_number: null,
    account_number: null,
    beneficiary_info: null,
    assigned_agent_id: null,
    buffer_agent_id: null,
    call_center_id: null,
    user_id: null,
    stage_id: null,
    pipeline_id: null,
    lead_value: null,
    created_at: null,
    updated_at: null,
    last_contacted_at: null,
});

